version: "2"
services:
  users:
    cpus: 0.5
    build:
      context: ${CONTEXT_PATH:-.}/bot
    container_name: users
    environment:
      TARGET_URL: http://192.168.123.3
    networks:
      subnet:
        ipv4_address: 192.168.123.2
  web:
    cpus: 0.5
    image: docker.pengyihao.top/pyh23/cmsms:2.2.9.1-installed
    depends_on:
      - mysql
    ports:
      - 8000:80
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      subnet:
        ipv4_address: 192.168.123.3
    command:
      [
        "/bin/bash",
        "-c",
        "mkdir -p /applog; apache2-foreground 2>&1 > /applog/app.log",
      ]
    x-app-log: "/applog"

  mysql:
    cpus: 0.5
    image: docker.pengyihao.top/pyh23/mysql:5.7-cmsms-installed
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cmsms
    networks:
      subnet:
        ipv4_address: 192.168.123.4

networks:
  subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.123.0/24

x-steps:
  - blocking: false
    command:
      - python
      - gen.py
    name: normal
    service: users

  - name: "Wait for 10min"
    service: users
    command: ["sleep", "600"]
    blocking: true

  - blocking: false
    command:
      - python
      - attack.py
    name: attacking
    is_attack: true
    service: users

  - name: "Wait for 10min"
    service: users
    command: ["sleep", "600"]
    blocking: true
