version: "2"
services:
  users:
    build:
      context: ${CONTEXT_PATH:-.}/bot
    container_name: users
    environment:
      TARGET_URL: https://192.168.123.3:8443
    networks:
      subnet:
        ipv4_address: 192.168.123.2
  web:
    build:
      context: ${CONTEXT_PATH:-.}
    # image: docker.pengyihao.top/vulhub/solr:8.2.0
    ports:
      - 8443:8443
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/java-agent.jar"
      LD_LIBRARY_PATH: "/quicklog"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -k -f https://localhost:8443/accounting/control/main || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      subnet:
        ipv4_address: 192.168.123.3
    x-app-log: "/usr/src/apache-ofbiz/runtime/logs"

networks:
  subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.123.0/24

x-steps:
  - blocking: false
    command:
      - python
      - gen.py
    name: normal
    service: users

  - blocking: false
    command:
      - python
      - custom_normal.py
    name: custom-normal
    service: users

  - name: "Wait for 10min"
    service: users
    command: ["sleep", "600"]
    blocking: true

  - blocking: false
    command:
      - python
      - attack.py
    name: attacking
    is_attack: true
    service: users

  - name: "Wait for 10min"
    service: users
    command: ["sleep", "600"]
    blocking: true
