// Auto generated by configure.py.
// Do not change it manually.

#define CONTAINER_NUMS 1
const int container_pids[] = {37842};

#define HACK_LEN 4
const int key_ips[CONTAINER_NUMS][HACK_LEN] = {
    {0x0a00000a, 0x0a00000b, 0x0a00000c, 0x0a00000d}
};
const int src_ips[CONTAINER_NUMS][HACK_LEN] = {
    {0xac110002, 0xac110002, 0xac110002, 0xac110002}
};
const int gateway_ips[CONTAINER_NUMS][HACK_LEN] = {
    {0xac110002, 0xac110002, 0xac110002, 0xac110002}
};
const int dst_ips[CONTAINER_NUMS][HACK_LEN] = {
    {0xaa01000a, 0xaa01000b, 0x0afa000b, 0x0afa000c}
};
