/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LoggingAgent_TomcatSocketProcessorBaseAdvice */

#ifndef _Included_LoggingAgent_TomcatSocketProcessorBaseAdvice
#define _Included_LoggingAgent_TomcatSocketProcessorBaseAdvice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LoggingAgent_TomcatSocketProcessorBaseAdvice
 * Method:    log
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LoggingAgent_00024TomcatSocketProcessorBaseAdvice_log
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
