/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LoggingAgent_ConstructorAdvice */

#ifndef _Included_LoggingAgent_ConstructorAdvice
#define _Included_LoggingAgent_ConstructorAdvice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LoggingAgent_ConstructorAdvice
 * Method:    log
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LoggingAgent_00024ConstructorAdvice_log
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
