/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LoggingAgent_CallableAdvice */

#ifndef _Included_LoggingAgent_CallableAdvice
#define _Included_LoggingAgent_CallableAdvice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LoggingAgent_CallableAdvice
 * Method:    log
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LoggingAgent_00024CallableAdvice_log
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
