/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LoggingAgent_RunnableAdvice */

#ifndef _Included_LoggingAgent_RunnableAdvice
#define _Included_LoggingAgent_RunnableAdvice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LoggingAgent_RunnableAdvice
 * Method:    log
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LoggingAgent_00024RunnableAdvice_log
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
