/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LoggingAgent_TomcatSocketWrapperBaseAdvice */

#ifndef _Included_LoggingAgent_TomcatSocketWrapperBaseAdvice
#define _Included_LoggingAgent_TomcatSocketWrapperBaseAdvice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LoggingAgent_TomcatSocketWrapperBaseAdvice
 * Method:    log
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LoggingAgent_00024TomcatSocketWrapperBaseAdvice_log
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
