FROM ubuntu:22.04
USER root

# basic deps
RUN apt-get update
RUN apt-get install -y curl git build-essential python3 python-is-python3

# install modded node
WORKDIR /tmp
RUN git clone http://10.1.0.1:8929/finall1008/nodejs-instrumentation.git
WORKDIR /tmp/nodejs-instrumentation
RUN git checkout pyh-v12.22.12

RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get install -y python2.7

RUN ./configure
RUN make -j 5
RUN make install

WORKDIR /root
