from config_attack import ip_list

BEGIN_CONTENT = """
#ifndef IP_LIST_H_
#define IP_LIST_H_

"""

END_CONTENT = """
#endif // IP_LIST_H_
"""


with open("ip_list.h", "w") as out:
    out.write("// Auto generated by configure.py.\n")
    out.write("// Do not change it manually.\n")

    out.write(BEGIN_CONTENT)

    out.write("const char *ip_list[][2] = {\n")

    for key, val in ip_list.items():
        out.write(f'   {{"{val}", "{key}"}},\n')

    out.write("};\n")
    out.write(END_CONTENT)
