// Auto generated by configure.py.
// Do not change it manually.

#ifndef IP_LIST_H_
#define IP_LIST_H_

const char *ip_list[][2] = {
   {"10.0.0.10", "170.1.0.10"},
   {"10.0.0.11", "170.1.0.11"},
};

#endif // IP_LIST_H_
